resources:
  limits: {}
  #   cpu: 250m
  #   memory: 1Gi
  requests: 
    cpu: 3000m
    memory: 3000Mi

postgresqlExtendedConf:
   wal_level: logical
   max_wal_senders: 20
   max_replication_slots: 10
   max_connections: 1000

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 64Gi
